### ISSUE TITLE
Improve code readability

### ISSUE THREAD

**Issue by WajahatAliAbid** [ghalib5000/Multi_File_Maker#1]
This code is very unreadable. Please use small methods and use good variable names. Look at best practices for coding to improve this code. Please improve code readability by using small methods that say what they do. This will help with collaboration aspect of this code as well.

**Comment by ghalib5000** [comment]
sure will look it up in a couple of days

**Comment by WajahatAliAbid** [comment]
looking forward to the update :)

**Comment by ghalib5000** [comment]
so about imporving the code readablity.... i forgot how this code even worked and can't understand it completly
so if you want, you can do whatever you like with this.....code :)

**Comment by ghalib5000** [comment]
it will take some time if i ever re write this code again

**Comment by WajahatAliAbid** [comment]
Tell me in detail what this code does and I can do something about it

**Comment by ghalib5000** [comment]
well......this code basically takes "text A" and copies is after "text B" with slight alterations, for example , the first line of text B contains location "D:/first " while the second line of text B contains location "D:/second " and the text A contains "hello worlds" so this program will generate a file that will have the output as:
D:/first hello wolrds
D:/second hello worlds
the text of both the A and B was given in a file
the text file of B contained multiple lines while the text file of A contained a single line which would be concatenated with the text of B

i also added a functionality so that you could add multiples line in text B to automate all the concatenating that needs to be done
for this i took the "END" word and placed it at every end of B and it's respective A and whenever one line would read END it knew that it has to count upto this point and concat the A text with the B text that is before the END and then move on from there

**Comment by WajahatAliAbid** [comment]
That doesn't make much sense to me, can you elaborate?

**Comment by ghalib5000** [comment]
well let's take it step by step.
first, the program takes 2 files as input. we'll call them A and B
next, the program takes a single line from file A and joins it with All the text lines in File B and gives the output in another file
understood?

**Comment by ghalib5000** [comment]
basically you can understand this as there is an attendance sheet as file B and "present" as File A
so every line(that is every student) should be shown as present in the result
